# Generated by Django 4.2.4 on 2023-08-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour_and_Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favouriteGeneralColour', models.CharField(max_length=200)),
                ('worstGeneralColour', models.CharField(max_length=200)),
                ('cuteColour', models.CharField(max_length=200)),
                ('favouriteDressColour', models.CharField(max_length=200)),
                ('favouriteTraditionalDressColor', models.CharField(max_length=200)),
                ('favouriteCoverShoesBraceletsColor', models.CharField(max_length=200)),
                ('favouriteOutfit', models.TextField()),
                ('worstOutfit', models.TextField()),
                ('favouriteShoeWear', models.TextField()),
                ('worstShoeWear', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favouriteMovieOfAllTime', models.CharField(max_length=400)),
                ('favouriteSeriesOfAllTime', models.CharField(max_length=400)),
                ('favouriteBollywoodMovieOfAllTime', models.CharField(max_length=400)),
                ('favouriteBollywoodSeriesOfAllTime', models.CharField(max_length=400)),
                ('favouriteBookOrAuthor', models.CharField(max_length=400)),
                ('favouriteGeneralGenre', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTreats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favouriteFood', models.CharField(max_length=200)),
                ('worstFood', models.CharField(max_length=200)),
                ('favouriteIceCreamFlavour', models.CharField(max_length=200)),
                ('worstIceCreamFlavour', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MusicSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allTimeFavouriteSong', models.CharField(max_length=400)),
                ('allTimeFavouriteSinger', models.CharField(max_length=400)),
                ('allTimeFavouriteBollywoodSong', models.CharField(max_length=400)),
                ('allTimeFavouriteBollywoodSinger', models.CharField(max_length=400)),
                ('favouriteGenre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favouritePasttime', models.TextField()),
                ('wantToLearn', models.TextField()),
                ('catOrDog', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipsSentiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allTimeBestMemory', models.TextField()),
                ('allTimeBestMemoryWithMe', models.TextField()),
                ('bestGiftEverReceived', models.TextField()),
                ('mostCherishedGiftFromMe', models.TextField()),
                ('unforgettableGestureFromSomeone', models.TextField()),
                ('unforgettableGestureFromMe', models.TextField()),
                ('valueMostInRelationship', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favouritePlace', models.CharField(max_length=200)),
                ('dreamDestination', models.CharField(max_length=200)),
            ],
        ),
    ]
