# Generated by Django 4.2.4 on 2023-08-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_rename_favouritebollywoodmovieofalltime_entertainment_favourite_book_or_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour_and_fashion',
            old_name='cuteColour',
            new_name='cute_color',
        ),
        migrations.RenameField(
            model_name='colour_and_fashion',
            old_name='favouriteCoverShoesBraceletsColor',
            new_name='favourite_cover_shoes_bracelets_color',
        ),
        migrations.RenameField(
            model_name='colour_and_fashion',
            old_name='favouriteDressColour',
            new_name='favourite_dress_color',
        ),
        migrations.RenameField(
            model_name='colour_and_fashion',
            old_name='favouriteGeneralColour',
            new_name='favourite_general_color',
        ),
        migrations.RenameField(
            model_name='colour_and_fashion',
            old_name='favouriteOutfit',
            new_name='favourite_outfit',
        ),
        migrations.RenameField(
            model_name='colour_and_fashion',
            old_name='favouriteShoeWear',
            new_name='favourite_shoe_wear',
        ),
        migrations.RenameField(
            model_name='colour_and_fashion',
            old_name='favouriteTraditionalDressColor',
            new_name='favourite_traditional_dressColor',
        ),
        migrations.RenameField(
            model_name='colour_and_fashion',
            old_name='worstGeneralColour',
            new_name='worst_general_color',
        ),
        migrations.RenameField(
            model_name='colour_and_fashion',
            old_name='worstOutfit',
            new_name='worst_outfit',
        ),
        migrations.RenameField(
            model_name='colour_and_fashion',
            old_name='worstShoeWear',
            new_name='worst_shoe_wear',
        ),
    ]
