# Generated by Django 4.2.4 on 2023-08-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_rename_cutecolour_colour_and_fashion_cute_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour_and_fashion',
            old_name='favourite_traditional_dressColor',
            new_name='favourite_traditional_dress_color',
        ),
        migrations.RenameField(
            model_name='foodtreats',
            old_name='favourite_iceCream_flavour',
            new_name='favourite_ice_cream_flavour',
        ),
        migrations.RenameField(
            model_name='foodtreats',
            old_name='worst_icecream_flavour',
            new_name='worst_ice_cream_flavour',
        ),
        migrations.RenameField(
            model_name='personallifestyle',
            old_name='favourite_pasttime',
            new_name='favourite_past_time',
        ),
    ]
